pokerstats/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from root.views import (
    contact_view,
    error_view,
    root_view,
)

from user.views import CustomPasswordChangeView

urlpatterns = [
    path('', root_view, name="home"),
    path('accounts/password/change/', CustomPasswordChangeView.as_view(), name="account_change_password"),
    path('accounts/', include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('contact/', contact_view, name="contact"),
    path('error/<str:error_message>/', error_view, name="error"),
    path('tournament/', include("tournament.urls"), name="tournament"),
    path('user/', include("user.urls"), name="user"),
    path('tournament_analytics/', include("tournament_analytics.urls"), name="tournament_analytics"),
    path('tournament_group/', include("tournament_group.urls"), name="tournament_group"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tournament/urls.py
from django.urls import include, path

from tournament.views import (
    complete_tournament,
    eliminate_player_from_tournament,
    invite_player_to_tournament,
    get_tournament_structure,
    join_tournament,
    rebuy_player_in_tournament,
    remove_player_from_tournament,
    split_eliminate_player_from_tournament,
    start_tournament,
    tournament_admin_view,
    tournament_backfill_view,
    tournament_create_view,
    tournament_edit_view,
    tournament_list_view,
    tournament_structure_create_view,
    tournament_view,
    undo_completed_at,
    undo_started_at,
    uninvite_player_from_tournament,
)

app_name = 'tournament'

urlpatterns = [
    path('complete/<int:pk>/', complete_tournament, name="complete"),
    path('create_tournament/', tournament_create_view, name="create_tournament"),
    path('create_tournament_structure/', tournament_structure_create_view, name="create_tournament_structure"),
    path('eliminate_player/<int:tournament_id>/<int:eliminator_id>/<int:eliminatee_id>/', eliminate_player_from_tournament, name="eliminate_player"),
    path('invite_player_to_tournament/<int:player_id>/<int:tournament_id>/', invite_player_to_tournament, name="invite_player"),
    path('get_tournament_structure/', get_tournament_structure, name="get_tournament_structure"),
    path('join_tournament/<int:pk>/', join_tournament, name="join_tournament"),
    path('player_rebuy/<int:player_id>/<int:tournament_id>/', rebuy_player_in_tournament, name="player_rebuy"),
    path('remove_player/<int:user_id>/<int:tournament_id>/', remove_player_from_tournament, name="remove_player"),
    path('split_eliminate_player/<int:tournament_id>/<str:eliminator_ids>/<int:eliminatee_id>/', split_eliminate_player_from_tournament, name="split_eliminate_player"),
    path('start/<int:pk>/', start_tournament, name="start"),
    path('tournament_admin_view/<int:pk>/', tournament_admin_view, name="tournament_admin_view"),
    path('tournament_backfill_view/<int:pk>/', tournament_backfill_view, name="tournament_backfill"),
    path('tournament_edit/<int:pk>/', tournament_edit_view, name="tournament_edit"),
    path('tournament_list/', tournament_list_view, name="tournament_list"),
    path('tournament_view/<int:pk>/', tournament_view, name="tournament_view"),
    path('undo_complete/<int:pk>/', undo_completed_at, name="undo_complete"),
    path('undo_started/<int:pk>/', undo_started_at, name="undo_started"),
    path('uninvite/<int:player_id>/<int:tournament_id>/', uninvite_player_from_tournament, name="uninvite"),
]

tournament_group/urls.py
from django.urls import include, path

from tournament_group.views import (
	add_tournament_to_group,
	add_user_to_group,
	fetch_rbg_colors,
	fetch_tournament_group_eliminations_and_rebuys_data,
	fetch_tournament_group_net_earnings_data,
	fetch_tournament_group_pot_contributions_data,
	fetch_tournament_group_touraments_played_data,
	remove_tournament_from_group,
	remove_user_from_group,
	tournament_group_create_view,
	tournament_group_update_view,
	update_tournament_group_title,
	view_tournament_group
)

app_name = 'tournament_group'

urlpatterns = [
    path('add_user_to_group/<int:user_id>/<int:tournament_group_id>/', add_user_to_group, name="add_user_to_group"),
    path('add_tourament_to_group/<int:tournament_id>/<int:tournament_group_id>/', add_tournament_to_group, name="add_tournament_to_group"),
    path('remove_tournament_from_group/<int:tournament_id>/<int:tournament_group_id>/', remove_tournament_from_group, name="remove_tournament_from_group"),
    path('fetch_elim_and_rebuys_data/<int:pk>/', fetch_tournament_group_eliminations_and_rebuys_data, name="fetch_elim_and_rebuys_data"),
    path('fetch_net_earnings_data/<int:pk>/', fetch_tournament_group_net_earnings_data, name="fetch_net_earnings_data"),
    path('fetch_pot_contributions_data/<int:pk>/', fetch_tournament_group_pot_contributions_data, name="fetch_pot_contributions_data"),
    path('fetch_rbg_colors/<int:num_colors>/', fetch_rbg_colors, name="fetch_rbg_colors"),
    path('fetch_tournaments_played_data/<int:pk>/', fetch_tournament_group_touraments_played_data, name="fetch_tournaments_played_data"),
    path('create/', tournament_group_create_view, name="create"),
    path('remove_user_from_group/<int:user_id>/<int:tournament_group_id>/', remove_user_from_group, name="remove_user_from_group"),
    path('update/<int:pk>/', tournament_group_update_view, name="update"),
    path('update_tournament_group_title/<int:tournament_group_id>/<path:title>/', update_tournament_group_title, name="update_tournament_group_title"),
    path('view_tournament_group/<int:pk>/', view_tournament_group, name="view"),
]

user/urls.py
from django.urls import include, path

from user.views import (
    cannot_edit_others_profile,
    user_profile_view,
)

app_name = 'user'

urlpatterns = [
    path('profile/<int:pk>/', user_profile_view, name="profile"),
    path('cannot_edit_others_profile/', cannot_edit_others_profile, name="cannot_edit_others_profile"),
]

tournament_group/forms.py
from django import forms

from tournament_group.models import TournamentGroup

class CreateTournamentGroupForm(forms.ModelForm):
    class Meta:
        model = TournamentGroup
        fields = ['title']

tournament_group/views.py
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from datetime import datetime
import random
import json

from tournament.models import Tournament, TournamentPlayer, TournamentState
from tournament_group.forms import CreateTournamentGroupForm
from tournament_group.models import TournamentGroup
from tournament_group.util import (
	build_json_from_net_earnings_data,
	build_json_from_pot_contributions_data,
	build_json_from_eliminations_and_rebuys_data,
	build_json_from_tournaments_played_data
)
from user.models import User

@login_required
def tournament_group_create_view(request, *args, **kwargs):
	context = {}
	try:
		if request.method == 'POST':
			form = CreateTournamentGroupForm(request.POST)
			if form.is_valid():
				tournament_group = TournamentGroup.objects.create_tournament_group(
					admin = request.user,
					title = form.cleaned_data['title'],
				)
				messages.success(request, "Tournament Group Created!")

				return redirect('tournament_group:view', pk=tournament_group.id)
		else:
			form = CreateTournamentGroupForm()
		context['form'] = form
	except Exception as e:
		messages.error(request, e.args[0])
		form = CreateTournamentGroupForm()
		context['form'] = form
	return render(request=request, template_name='tournament_group/create_tournament_group.html', context=context)

@login_required
def tournament_group_update_view(request, *args, **kwargs):
	context = {}
	try:
		pk = kwargs['pk']
		tournament_group = TournamentGroup.objects.get_by_id(pk)
		if tournament_group == None:
			raise ValidationError("Our records indicate that TournamentGroup does not exist.")

		if request.user != tournament_group.admin:
			return redirect("tournament_group:view", pk=tournament_group.id)

		context['tournament_group'] = tournament_group

		current_users = tournament_group.get_users()
		context['current_users'] = current_users

		# Current start_at date.
		start_at_date = tournament_group.start_at
		if start_at_date != None:
			context['start_at_date_raw'] = start_at_date
			context['start_at_date'] = datetime.strftime(start_at_date, "%Y/%m/%d %H:%M")

		# Current end_at date
		end_at_date = tournament_group.end_at
		if end_at_date != None:
			context['end_at_date_raw'] = end_at_date
			context['end_at_date'] = datetime.strftime(end_at_date, "%Y/%m/%d %H:%M")

		# Get the updated title
		new_title = request.POST.get("new_title")
		if new_title == None or new_title == "":
			new_title = tournament_group.title
		context['new_title'] = new_title

		if_title_save_btn_enabled = False
		if new_title != tournament_group.title:
			if_title_save_btn_enabled = True
		context['if_title_save_btn_enabled'] = if_title_save_btn_enabled

		# Search for users with htmx
		search = request.GET.get("search")
		if search != None and search != "":
			search_result_users = User.objects.all().filter(username__icontains=search)
			# Exclude the admin,
			search_result_users = search_result_users.exclude(email__iexact=request.user.email)
			# Exclude users who are already added
			for user in current_users:
				search_result_users = search_result_users.exclude(email__iexact=user.email)
			context['search_result_users'] = search_result_users
			context['search'] = search

		current_tournaments = tournament_group.get_tournaments()
		context['current_tournaments'] = current_tournaments

		# Search for tournaments with htmx
		search_tournaments = request.GET.get("search_tournaments")
		if search_tournaments != None and search_tournaments != "":
			tournament_search_result = Tournament.objects.all().filter(title__icontains=search_tournaments)
			
			# Exclude Tournaments that are already added
			for tournament in current_tournaments:
				tournament_search_result = tournament_search_result.exclude(id=tournament.id)

			# Exclude tournaments where:
			# 1. None of the users in this group have played.
			# 2. Not completed
			# 3. Not within the allowed date range
			for tournament in tournament_search_result:
				if not TournamentGroup.objects.has_at_least_one_user_played_in_tournament(group=tournament_group, tournament=tournament):
					tournament_search_result = tournament_search_result.exclude(id=tournament.id)
				if tournament.get_state() != TournamentState.COMPLETED:
					tournament_search_result = tournament_search_result.exclude(id=tournament.id)
				if tournament.completed_at != None:
					if tournament_group.start_at != None and tournament.completed_at < tournament_group.start_at:
						tournament_search_result = tournament_search_result.exclude(id=tournament.id)
					if tournament_group.end_at != None and tournament.completed_at > tournament_group.end_at:
						tournament_search_result = tournament_search_result.exclude(id=tournament.id)

			context['tournament_search_result'] = tournament_search_result
			context['search_tournaments'] = search_tournaments

		# Update end_at date with htmx
		end_at_date = request.GET.get("update_end_at_date")
		if end_at_date != None:
			updated_group = TournamentGroup.objects.update_end_at_date(
				user = request.user,
				group = tournament_group,
				end_at_date = end_at_date
			)
			context['end_at_date_raw'] = updated_group.end_at
			context['end_at_date'] = datetime.strftime(updated_group.end_at, "%Y/%m/%d")

		# Update start_at date with htmx
		start_at_date = request.GET.get("update_start_at_date")
		if start_at_date != None:
			updated_group = TournamentGroup.objects.update_start_at_date(
				user = request.user,
				group = tournament_group,
				start_at_date = start_at_date
			)
			context['start_at_date_raw'] = updated_group.start_at
			context['start_at_date'] = datetime.strftime(updated_group.start_at, "%Y/%m/%d")

		current_tournaments = tournament_group.get_tournaments()
		context['current_tournaments'] = current_tournaments

		context['edit_mode'] = True

		# Remove tournaments that do not fall within new date range.
		# Get an updated version of the group at this point b/c if may have changed.
		tournament_group = TournamentGroup.objects.get_by_id(tournament_group.id)
		removed_tournaments = []
		for tournament in current_tournaments:
			if tournament.completed_at != None:
				if tournament_group.end_at != None and tournament.completed_at > tournament_group.end_at:
					TournamentGroup.objects.remove_tournament_from_group(
							admin = tournament_group.admin,
							group = tournament_group,
							tournament = tournament
						)
					removed_tournaments.append(tournament)
					continue
				if tournament_group.start_at != None and tournament.completed_at < tournament_group.start_at:
					TournamentGroup.objects.remove_tournament_from_group(
							admin = tournament_group.admin,
							group = tournament_group,
							tournament = tournament
						)
					removed_tournaments.append(tournament)
					continue
					
		if len(removed_tournaments) > 0:
			warning_message = "Removed tournaments: "
			for index,tournament in enumerate(removed_tournaments):
				if index > 0:
					warning_message += ", "
				warning_message += f"({tournament.title})"
			messages.warning(request, warning_message)
			current_tournaments = tournament_group.get_tournaments()
			context['current_tournaments'] = current_tournaments
	except Exception as e:
		messages.error(request, e.args[0])
	return render(request=request, template_name='tournament_group/update_tournament_group.html', context=context)


@login_required
def view_tournament_group(request, *args, **kwargs):
	context = {}
	try:
		pk = kwargs['pk']
		tournament_group = TournamentGroup.objects.get_by_id(pk)
		if tournament_group == None:
			raise ValidationError("Our records indicate that TournamentGroup does not exist.")

		context['tournament_group'] = tournament_group

		users = tournament_group.get_users()
		context['users'] = users

		if request.user not in users:
			return redirect("error", error_message="You are not part of that Tournament Group.")

		tournaments = tournament_group.get_tournaments()
		context['tournaments'] = tournaments

		start_at = tournament_group.start_at
		context['start_at'] = start_at

		end_at = tournament_group.end_at
		context['end_at'] = end_at

		if start_at and end_at:
			today = timezone.now()
			if start_at > today:
				context['days_until_start'] = (start_at - today).days
			if today > end_at:
				context['days_since_end'] = (today - end_at).days
			progress = tournament_group.get_progress()
			duration = tournament_group.get_group_duration()
			days_remaining = tournament_group.get_days_remaining()
			pct = progress / duration
			context['progress_pct'] = int(pct * 100)
			context['duration'] = duration
			context['progress'] = progress
			context['days_remaining'] = days_remaining

		context['edit_mode'] = False
	except Exception as e:
		messages.error(request, e.args[0])
	return render(request=request, template_name='tournament_group/tournament_group_view.html', context=context)

@login_required
def fetch_tournament_group_net_earnings_data(request, *args, **kwargs):
	context = {}
	try:
		pk = kwargs['pk']
		tournament_group = TournamentGroup.objects.get_by_id(pk)
		if tournament_group == None:
			raise ValidationError("Our records indicate that TournamentGroup does not exist.")

		net_earnings_data = TournamentGroup.objects.build_group_net_earnings_data(
			group = tournament_group
		)
		context['net_earnings_data'] = build_json_from_net_earnings_data(net_earnings_data)
	except Exception as e:
		error = {
			'error': "Unable to retrieve net earnings data.",
			'message': f"{e.args[0]}"
		}
		return JsonResponse(error, status=200)
	return JsonResponse(context, status=200)

@login_required
def fetch_rbg_colors(request, *args, **kwargs):
	context = {}
	try:
		num_colors = kwargs['num_colors']
		colors = {}
		for x in range(0, int(num_colors)):
			color_list = list(random.choices(range(256), k=3))

tournament_group/templates/tournament_group/snippets/display_user_list_snippet_edit_mode.html
{% if users %}
<div class="mt-4">
  <ul class="list-group">
  {% for user in users %}
    {% if user == tournament_group.admin %}
      <div class="list-group-item">
        <div class="user-username"><span class="user-admin-text">(Admin)</span>{{user.username}}</div>
      </div>
      {% else %}
        <div class="list-group-item d-flex flex-row">
        <a href="{% url 'tournament_group:remove_user_from_group' user_id=user.id tournament_group_id=tournament_group.id %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-x-square remove-user-icon" viewBox="0 0 16 16">
          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
          <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
          </svg>
        </a>
        <div class="user-username">{{user.username}}</div>
    </div>
    {% endif %}
  {% endfor %}
  </ul>
</div>

<style type="text/css">
  .user-admin-text {
    font-weight: 500;
    margin-right: 6px;
  }

  .user-username {
    align-self: center;
  }

  .remove-user-icon:hover {
    cursor: pointer;
    background: #c3c3c3;
  }

  .remove-user-icon {
    background-color: #d9534f;
    margin-right: 16px;
    color: black;
    border-radius: 6px;
  }

  @media only screen and (max-width: 500px) {
    .user-username {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      text-align: left;
      font-size: 13px;
    }
  }
  @media only screen and (min-width: 500px) and (max-width: 600px) {
    .user-username {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      text-align: left;
      font-size: 13px;
    }
  }

  @media only screen and (min-width: 600px) and (max-width: 768px) {
    .user-username {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      text-align: left;
      font-size: 16px;
    }
  }

  @media only screen and (min-width: 768px) and (max-width: 992px) {
    .user-username {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      text-align: left;
      font-size: 16px;
    }
  }

  @media only screen and (min-width: 992px) and (max-width: 1200px) {
    .user-username {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      text-align: left;
      font-size: 16px;
    }
  }

  @media only screen and (min-width: 1200px) {
    .user-username {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      text-align: left;
      font-size: 16px;
    }
  }
</style>
{% endif %}

tournament_group/templates/tournament_group/snippets/tournament_groups_list_snippet.html
{% if tournament_groups %}
  <ul class="list-group">
  {% for tournament_group in tournament_groups %}
  <a href="{% url 'tournament_group:view' pk=tournament_group.id %}" class="list-group-item list-group-item-action ">
    <div class="d-flex flex-column">
      <div class="tournament-group-title">{{tournament_group.title}}</div>
      <small class="mb-1">Users: {{tournament_group.get_users|length}}</small>
      <small class="mb-1">Tournaments: {{tournament_group.get_tournaments|length}}</small>
    </div>
  </a>
  {% endfor %}
</ul>
{% endif %}

<style type="text/css">

  .tournament-group-title {
/*    align-self: center;*/
    font-weight: 450;
  }


  @media only screen and (max-width: 500px) {
    .tournament-group-title {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      max-width: 200px;
      text-align: left;
      font-size: 13px;
    }

    .tournament-date-container {
      font-size: 13px;
      width: 100px;
    }

    .tournament-state {
      font-size: 11px;
    }
  }

  @media only screen and (min-width: 500px) and (max-width: 600px) {
    .tournament-group-title {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      max-width: 200px;
      text-align: left;
      font-size: 13px;
    }
  }

  @media only screen and (min-width: 600px) and (max-width: 768px) {
    .tournament-group-title {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      max-width: 320px;
      text-align: left;
      font-size: 16px;
    }
  }

  @media only screen and (min-width: 768px) and (max-width: 992px) {
    .tournament-group-title {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      max-width: 380px;
      text-align: left;
      font-size: 16px;
    }
  }

  @media only screen and (min-width: 992px) and (max-width: 1200px) {
    .tournament-group-title {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      max-width: 480px;
      text-align: left;
      font-size: 16px;
    }
  }

  @media only screen and (min-width: 1200px) {
    .tournament-group-title {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      max-width: 700px;
      text-align: left;
      font-size: 16px;
    }
  }

</style>

tournament_group/templates/tournament_group/snippets/tournament_list_snippet.html
{% load humanize %}
{% load tournament_extras %}

{% if tournaments %}
  <ul class="list-group">
  {% for tournament in tournaments %}
  {% if edit_mode %}
  <div class="list-group-item d-flex flex-row justify-content-between">
  {% else %}
  <a href="{% url 'tournament:tournament_view' pk=tournament.id %}" class="list-group-item list-group-item-action d-flex flex-row justify-content-between">
  {% endif %}
    <div class="d-flex flex-row ">
      {% if edit_mode %}
      <a class="align-self-center" href="{% url 'tournament_group:remove_tournament_from_group' tournament_id=tournament.id tournament_group_id=tournament_group.id %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-x-square remove-user-icon" viewBox="0 0 16 16">
          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
          <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
        </svg>
      </a>
      <div class="tournament-title">
        <a href="{% url 'tournament:tournament_view' pk=tournament.id %}">
          {{tournament.title}}
        </a>
      </div>
      {% else %}
      <div class="tournament-title">{{tournament.title}}</div>
      {% endif %}
    </div>
    <div class="d-flex flex-column tournament-date-container">
      <div>{{tournament.started_at|naturalday|none_as_empty}}</div>
      <div class="tournament-state" style="font-weight: bold; color: {% if tournament.get_state_string == 'INACTIVE' %}#5cb85c;{% elif tournament.get_state_string == 'COMPLETED' %}#d9534f;{% else %}#0275d8;{% endif %}">
        {{tournament.get_state_string}}
      </div>
    </div>
  {% if edit_mode %}
  </div>
  {% else %}
  </a>
  {% endif %}


  {% endfor %}
</ul>
{% endif %}

<style type="text/css">

  .tournament-title {
    align-self: center;
  }

  .tournament-date-container{
    align-self: center;
  }

  @media only screen and (max-width: 500px) {
    .tournament-title {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      max-width: 200px;
      text-align: left;
      font-size: 13px;
    }

    .tournament-date-container {
      font-size: 13px;
      width: 100px;
    }

    .tournament-state {
      font-size: 11px;
    }
  }

  @media only screen and (min-width: 500px) and (max-width: 600px) {
    .tournament-title {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      max-width: 200px;
      text-align: left;
      font-size: 13px;
    }

    .tournament-date-container {
      font-size: 13px;
      width: 100px;
    }

    .tournament-state {
      font-size: 11px;
    }
  }

  @media only screen and (min-width: 600px) and (max-width: 768px) {
    .tournament-title {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      max-width: 320px;
      text-align: left;
      font-size: 16px;
    }

    .tournament-date-container {
      font-size: 16px;
      width: 120px;
    }

    .tournament-state {
      font-size: 14px;
    }
  }

  @media only screen and (min-width: 768px) and (max-width: 992px) {
    .tournament-title {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      max-width: 380px;
      text-align: left;
      font-size: 16px;
    }

    .tournament-date-container {
      font-size: 16px;
      width: 120px;
    }

    .tournament-state {
      font-size: 14px;
    }
  }

  @media only screen and (min-width: 992px) and (max-width: 1200px) {
    .tournament-title {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      max-width: 480px;
      text-align: left;
      font-size: 16px;
    }

    .tournament-date-container {
      font-size: 16px;
      width: 120px;
    }

    .tournament-state {
      font-size: 14px;
    }
  }

  @media only screen and (min-width: 1200px) {
    .tournament-title {
      overflow: hidden;
      white-space: wrap;
      text-overflow: ellipsis;
      max-width: 700px;
      text-align: left;
      font-size: 16px;
    }

    .tournament-date-container {
      font-size: 16px;
      width: 120px;
    }

    .tournament-state {
      font-size: 14px;
    }
  }

</style>

tournament_group/templates/tournament_group/snippets/tournament_search_results.html
<div id="id-tournament-search-results">
  {% if tournaments %}
    <ul class="list-group tournament-list-group">
    {% for tournament in tournaments %}
      <div class="tournament-list-item d-flex justify-content-between list-group-item list-group-item-action">
        <span class="tournament-title">{{tournament.title}}</span>
        {% if request.user == tournament_group.admin %}
        <a hx-post="{% url 'tournament_group:add_tournament_to_group' tournament_id=tournament.id tournament_group_id=tournament_group.id %}" hx-target="#body_container" hx-swap="innerHTML" class="btn btn-primary btn-sm" style="margin-left: 16px">Add</a>
        {% endif %}
      </div>
    {% endfor %}
  </ul>
  {% endif %}
</div>

<style type="text/css">
  .tournament-list-item {
    margin: auto;
  }
  .tournament-title {
    display: inline-flex;
    align-items: center;
  }
  .tournament-list-group {
    position: absolute;
    width: inherit;
    background: #fff;
    z-index: 9;
    min-width: 350px;
  }
</style>

tournament_group/templates/tournament_group/snippets/user_search_results.html
<div id="id-user-search-results">
  {% if users %}
    <ul class="list-group user-list-group">
    {% for user in users %}
      <div class="user-list-item d-flex justify-content-between list-group-item list-group-item-action">
        <span class="username">{{user.username}}</span>
        {% if request.user == tournament_group.admin %}
        <a hx-post="{% url 'tournament_group:add_user_to_group' user_id=user.id tournament_group_id=tournament_group.id %}" hx-target="#body_container" hx-swap="innerHTML" class="btn btn-primary btn-sm" style="margin-left: 16px">Add</a>
        {% endif %}
      </div>
    {% endfor %}
  </ul>
  {% endif %}
</div>

<style type="text/css">
  .user-list-item {
    margin: auto;
  }
  .username {
    display: inline-flex;
    align-items: center;
  }
  .user-list-group {
    position: absolute;
    width: inherit;
    background: #fff;
    z-index: 9;
    min-width: 350px;
  }
</style>