pokerstats/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from root.views import (
    contact_view,
    error_view,
    root_view,
)

from user.views import CustomPasswordChangeView

urlpatterns = [
    path('', root_view, name="home"),
    path('accounts/password/change/', CustomPasswordChangeView.as_view(), name="account_change_password"),
    path('accounts/', include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('contact/', contact_view, name="contact"),
    path('error/<str:error_message>/', error_view, name="error"),
    path('tournament/', include("tournament.urls"), name="tournament"),
    path('user/', include("user.urls"), name="user"),
    path('tournament_analytics/', include("tournament_analytics.urls"), name="tournament_analytics"),
    path('tournament_group/', include("tournament_group.urls"), name="tournament_group"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tournament/urls.py
from django.urls import include, path

from tournament.views import (
    complete_tournament,
    eliminate_player_from_tournament,
    invite_player_to_tournament,
    get_tournament_structure,
    join_tournament,
    rebuy_player_in_tournament,
    remove_player_from_tournament,
    split_eliminate_player_from_tournament,
    start_tournament,
    tournament_admin_view,
    tournament_backfill_view,
    tournament_create_view,
    tournament_edit_view,
    tournament_list_view,
    tournament_structure_create_view,
    tournament_view,
    undo_completed_at,
    undo_started_at,
    uninvite_player_from_tournament,
)

app_name = 'tournament'

urlpatterns = [
    path('complete/<int:pk>/', complete_tournament, name="complete"),
    path('create_tournament/', tournament_create_view, name="create_tournament"),
    path('create_tournament_structure/', tournament_structure_create_view, name="create_tournament_structure"),
    path('eliminate_player/<int:tournament_id>/<int:eliminator_id>/<int:eliminatee_id>/', eliminate_player_from_tournament, name="eliminate_player"),
    path('invite_player_to_tournament/<int:player_id>/<int:tournament_id>/', invite_player_to_tournament, name="invite_player"),
    path('get_tournament_structure/', get_tournament_structure, name="get_tournament_structure"),
    path('join_tournament/<int:pk>/', join_tournament, name="join_tournament"),
    path('player_rebuy/<int:player_id>/<int:tournament_id>/', rebuy_player_in_tournament, name="player_rebuy"),
    path('remove_player/<int:user_id>/<int:tournament_id>/', remove_player_from_tournament, name="remove_player"),
    path('split_eliminate_player/<int:tournament_id>/<str:eliminator_ids>/<int:eliminatee_id>/', split_eliminate_player_from_tournament, name="split_eliminate_player"),
    path('start/<int:pk>/', start_tournament, name="start"),
    path('tournament_admin_view/<int:pk>/', tournament_admin_view, name="tournament_admin_view"),
    path('tournament_backfill_view/<int:pk>/', tournament_backfill_view, name="tournament_backfill"),
    path('tournament_edit/<int:pk>/', tournament_edit_view, name="tournament_edit"),
    path('tournament_list/', tournament_list_view, name="tournament_list"),
    path('tournament_view/<int:pk>/', tournament_view, name="tournament_view"),
    path('undo_complete/<int:pk>/', undo_completed_at, name="undo_complete"),
    path('undo_started/<int:pk>/', undo_started_at, name="undo_started"),
    path('uninvite/<int:player_id>/<int:tournament_id>/', uninvite_player_from_tournament, name="uninvite"),
]

user/urls.py
from django.urls import include, path

from user.views import (
    cannot_edit_others_profile,
    user_profile_view,
)

app_name = 'user'

urlpatterns = [
    path('profile/<int:pk>/', user_profile_view, name="profile"),
    path('cannot_edit_others_profile/', cannot_edit_others_profile, name="cannot_edit_others_profile"),
]

tournament/views.py
import json
from decimal import Decimal
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone

from tournament_group.models import TournamentGroup
from tournament.forms import CreateTournamentForm, CreateTournamentStructureForm, EditTournamentForm
from tournament.models import (
	Tournament,
	TournamentStructure,
	TournamentState,
	TournamentInvite,
	TournamentPlayer,
	TournamentElimination,
	TournamentPlayerResult,
	TournamentRebuy,
	TournamentSplitElimination
)
from tournament.util import (
	PlayerTournamentData,
	payout_positions,
	PlayerEliminationsData,
	build_placement_string,
	PlayerTournamentPlacement,
	DID_NOT_PLACE_VALUE,
	build_elimination_event,
	build_rebuy_event,
	build_completion_event,
	build_in_progress_event,
	build_split_elimination_event,
	build_split_eliminations_data,
	build_player_eliminations_data_from_eliminations,
	build_player_eliminations_summary_data_from_eliminations,
	get_tournament_started_at
)
from user.models import User

@login_required
def tournament_create_view(request, *args, **kwargs):
	context = {}
	if request.method == 'POST':
		form = CreateTournamentForm(request.POST, user=request.user)
		if form.is_valid():
			tournament = Tournament.objects.create_tournament(
				user = request.user,
				title = form.cleaned_data['title'],
				tournament_structure = form.cleaned_data['tournament_structure'],
			)
			if tournament is not None:
				messages.success(request, "Tournament Created!")

			redirect_url = request.GET.get('next')
			if redirect_url is not None:
				return redirect(redirect_url)
			return redirect("tournament:tournament_view", pk=tournament.id)
	else:
		form = CreateTournamentForm(user=request.user)

	context['form'] = form
	return render(request=request, template_name='tournament/create_tournament.html', context=context)

@login_required
def tournament_list_view(request, *args, **kwargs):
	context = {}
	try:
		# The tournament where they are the admin
		context['tournaments'] = Tournament.objects.get_by_user(
			user=request.user
		).order_by("started_at")

		# The tournaments they have joined (with accepted invite) but are not admin
		joined_tournaments = Tournament.objects.get_joined_tournaments(
			user_id = request.user.id
		)
		joined_tournaments.sort(
			key=get_tournament_started_at
		)
		
		context['joined_tournaments'] = joined_tournaments

		# pending invites
		invites = TournamentInvite.objects.find_pending_invites_for_user(
			send_to_user_id = request.user.id
		)
		context['invites'] = invites

		# Tourament Groups
		tournament_groups = TournamentGroup.objects.get_tournament_groups(
			user_id = request.user.id
		)
		context['tournament_groups'] = tournament_groups
	except Exception as e:
		messages.error(request, e.args[0])
	return render(request=request, template_name="tournament/tournament_list.html", context=context)

@login_required
def tournament_view(request, *args, **kwargs):
	tournament = Tournament.objects.get_by_id(kwargs['pk'])
	return render_tournament_view(request, tournament.id)

@login_required
def start_tournament(request, *args, **kwargs):
	tournament_id = kwargs['pk']
	try:
		user = request.user
		
		# Verify the admin is performing this action
		verify_admin(
			user = user,
			tournament_id = tournament_id,
			error_message = "You are not the admin of this Tournament."
		)

		tournament = Tournament.objects.start_tournament(user=user, tournament_id=tournament_id)
	except Exception as e:
		messages.error(request, e.args[0])
		return redirect(request.META['HTTP_REFERER'])
	return redirect("tournament:tournament_view", pk=tournament_id)

@login_required
def complete_tournament(request, *args, **kwargs):
	tournament_id = kwargs['pk']
	try:
		user = request.user
		
		# Verify the admin is performing this action
		verify_admin(
			user = user,
			tournament_id = tournament_id,
			error_message = "You are not the admin of this Tournament."
		)

		tournament = Tournament.objects.complete_tournament(user, tournament_id)
	except Exception as e:
		messages.error(request, e.args[0])
		return redirect(request.META['HTTP_REFERER'])
	return redirect("tournament:tournament_view", pk=tournament_id)

@login_required
def undo_completed_at(request, *args, **kwargs):
	tournament_id = kwargs['pk']
	try:
		user = request.user

		# Verify the admin is performing this action
		verify_admin(
			user = user,
			tournament_id = tournament_id,
			error_message = "You are not the admin of this Tournament."
		)

		Tournament.objects.undo_complete_tournament(
			user = user,
			tournament_id = tournament_id
		)
	except Exception as e:
		messages.error(request, e.args[0])
		return redirect(request.META['HTTP_REFERER'])
	return redirect("tournament:tournament_view", pk=tournament_id)

@login_required
def undo_started_at(request, *args, **kwargs):
	tournament_id = kwargs['pk']
	try:
		user = request.user
		# Verify the admin is performing this action
		verify_admin(
			user = user,
			tournament_id = tournament_id,
			error_message = "You are not the admin of this Tournament."
		)

		Tournament.objects.undo_start_tournament(
			user = user,
			tournament_id = tournament_id
		)
	except Exception as e:
		messages.error(request, e.args[0])
		return redirect(request.META['HTTP_REFERER'])
	return redirect("tournament:tournament_view", pk=tournament_id)

"""
Join a Tournament given a TournamentInvite.
kwargs['id'] is the id of the TournamentInvite.
"""
@login_required
def join_tournament(request, *args, **kwargs):
	user = request.user
	try:
		invite = TournamentInvite.objects.get(pk=kwargs['pk'])
		if invite.send_to != user:
			messages.error(request, "That invitation wasn't for you.")
			return redirect("home")

		# Get the player and join the Tournament.
		player = TournamentPlayer.objects.get_tournament_player_by_user_id(
			tournament_id = invite.tournament.id,
			user_id = invite.send_to.id
		)
		TournamentPlayer.objects.join_tournament(
			player = player
		)
		messages.success(request, f"Joined {player.tournament.title}.")
		# return redirect("tournament:tournament_view", pk=invite.tournament.id)
	except Exception as e:
		messages.error(request, e.args[0])
	return redirect(request.META['HTTP_REFERER'])

"""
Uninvite a player from a tournament.
HTMX request for tournament_view
"""
@login_required
def uninvite_player_from_tournament(request, *args, **kwargs):
	user = request.user
	player_id = kwargs['player_id']
	tournament_id = kwargs['tournament_id']
	try:
		uninvited_user = TournamentInvite.objects.uninvite_player_from_tournament(
			admin_id = user.id,
			uninvite_user_id = player_id,
			tournament_id = tournament_id
		)
		messages.success(request, f"Uninvited {uninvited_user.username}.")
	except Exception as e:
		messages.error(request, e.args[0])
	return render_tournament_view(request, tournament_id)
	

"""
Remove a player from a tournament.
HTMX request for tournament_view
"""
@login_required
def remove_player_from_tournament(request, *args, **kwargs):
	user = request.user
	user_id = kwargs['user_id']
	tournament_id = kwargs['tournament_id']
	try:
		removed_user = TournamentPlayer.objects.remove_player_from_tournament(
			removed_by_user_id= user.id,
			removed_user_id=user_id,
			tournament_id=tournament_id
		)
		messages.success(request, f"Removed {removed_user.username}.")
	except Exception as e:
		messages.error(request, e.args[0])
	return redirect(request.META['HTTP_REFERER'])

"""
Invite a player to a tournament.
HTMX request for tournament_view
"""
@login_required
def invite_player_to_tournament(request, *args, **kwargs):
	try:
		user = request.user
		player_id = kwargs['player_id']
		tournament_id = kwargs['tournament_id']
		
		# Verify the admin is sending the invite
		verify_admin(
			user = user,
			tournament_id = tournament_id,
			error_message = "Only the admin can invite players."
		)

		invite = TournamentInvite.objects.send_invite(
			sent_from_user_id = user.id,
			send_to_user_id = player_id,
			tournament_id = tournament_id
		)
		return render_tournament_view(request, tournament_id)
	except Exception as e:
		messages.error(request, e.args[0])
	return render_tournament_view(request, tournament_id)

"""
Eliminate a player from a tournament.
Returns a generic HttpResponse with a status code representing whether it was successful or not.
If it was not successful, the user will be redirected to an error page.
"""
@login_required
def eliminate_player_from_tournament(request, *args, **kwargs):
	user = request.user
	try:
		# Who is doing the eliminating
		eliminator_id = kwargs['eliminator_id']

		# Who is being eliminated
		eliminatee_id = kwargs['eliminatee_id']

		# Tournament id where this is taking place
		tournament_id = kwargs['tournament_id']

		# Verify the admin is the one eliminating
		verify_admin(
			user = request.user,
			tournament_id = tournament_id,
			error_message = "Only the admin can eliminate players."
		)

		# All the validation is performed in the create_elimination function.
		elimination = TournamentElimination.objects.create_elimination(
			tournament_id = tournament_id,
			eliminator_id = eliminator_id,
			eliminatee_id = eliminatee_id
		)
	except Exception as e:
		messages.error(request, e.args[0])
		return HttpResponse(content_type='application/json', status=400)
	return HttpResponse(content_type='application/json', status=200)

"""
Perform a split elimination.
"""
@login_required
def split_eliminate_player_from_tournament(request, *args, **kwargs):
	user = request.user
	try:
		# Who is doing the eliminating (this is a comma separated list of player ids)
		eliminator_ids = kwargs['eliminator_ids']

		# Who is being eliminated
		eliminatee_id = kwargs['eliminatee_id']

		# Tournament id where this is taking place
		tournament_id = kwargs['tournament_id']

tournament/templates/tournament/snippets/eliminations_detail_table.html
{% load tournament_extras %}

{% if results and eliminations_data|length > 0 %}

<div class="eliminations-detail-table  table-responsive">
	<p class="eliminations-detail-table-header">Eliminations</p>
  <table class="table ">
    <thead>
      <tr>
        <th scope="col"><div class="eliminations-detail-table-col">Player</div></th>
        <th scope="col"><div class="eliminations-detail-table-col">Eliminated</div></th>
      </tr>
    </thead>
    <tbody>
    	{% for elimination_data in eliminations_data %}
    	<tr>
	      <td scope="row">
	      	<div class="eliminations-detail-table-row">
	      		{{elimination_data.player_username}}
	      	</div>
	    	</td>
	    	<td>
	      	<div class="eliminations-detail-table-row d-flex flex-column">
	      		{% for username in elimination_data.eliminated_player_usernames %}
	      			<span>{{username}}</span>
	      		{% endfor %}
	      	</div>
	    	</td>
	    </tr>
    	{% endfor %}
    </tbody>
  </table>
</div>

<script type="text/javascript">
  // Initialize tooltip plugin
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

<style type="text/css">

	td {
		vertical-align: middle;
	}

	@media only screen and (max-width: 500px) {

		.eliminations-detail-table-header {
			font-size: 16px;
			font-weight: 400;
			margin-left: 8px;
			margin-bottom: 8px;
		}

		.eliminations-detail-table-col {
			font-size: 12px;
			text-align: left;
		}

		.eliminations-detail-table-row {
			font-size: 12px;
			text-align: left;
		}

    .eliminations-detail-table {
			padding: 4px;
			background-color: #f2f2f2;
			border-radius: 8px;
			margin-top: 16px;
    }

		.eliminations-detail-table-username {
			overflow: hidden;
			white-space: nowrap;
			text-overflow: ellipsis;
			max-width: 100px;
			text-align: left;
			font-weight: 600;
		}

		.eliminations-detail-string {
			font-size: 10px;
			font-weight: 600;
		}
  }

  @media only screen and (min-width: 501px) {
  	.eliminations-detail-table-header {
			font-size: 20px;
			font-weight: 400;
			margin-left: 8px;
			margin-bottom: 8px;
		}

    .eliminations-detail-table-col {
      font-size: 16px;
      text-align: left;
      vertical-align: middle;
    }

    .eliminations-detail-table-row {
      font-size: 16px;
      overflow: hidden;
      white-space: nowrap;
      text-overflow: ellipsis;
    }

    .eliminations-detail-table {
      padding: 16px;
      background-color: #f2f2f2;
      border-radius: 8px;
      margin-top: 24px;
    }

    .eliminations-detail-username {
			overflow: hidden;
			white-space: nowrap;
			text-overflow: ellipsis;
			max-width: 380px;
			text-align: left;
			font-weight: 500;
			color: #292b2c;
		}

		.eliminations-detail-string {
			font-size: 12px;
			font-weight: 600;
		}
  }
</style>

{% endif %}

tournament/templates/tournament/snippets/player_remove_modal.html
<!-- Modal -->
{% for player in players %}
  <div class="modal fade" id="id_remove_modal_{{player.user.id}}" tabindex="-1" aria-labelledby="{{player.user.username}} Remove Modal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="id_remove_modal_title">
            Remove {{player.user.username}}
          </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body d-flex flex-column">
          Are you sure you want to remove {{player.user.username}} from the tournament?
        </div>
        <div class="modal-footer" id="id_elim_model_button_container">
          <button class="btn btn-danger" hx-get="{% url 'tournament:remove_player' user_id=player.user.id tournament_id=tournament.id %}" hx-trigger="click" hx-target="#body_container">Remove</button>
        </div>
      </div>
    </div>
  </div>
{% endfor %}

tournament/templates/tournament/snippets/tournament_players_inactive_state.html
{% load tournament_extras %}

{% if tournament.get_state_string == "INACTIVE" %}
{% if players or invites %}

<div class="mt-3 players-container table-responsive" id="id_players_container">
  <table class="table">
  <thead>
    <tr>
      <th scope="col player-col">Player</th>
      <th scope="col player-col">Status</th>
      {% if request.user == tournament.admin %}
      <th scope="col player-col">Action</th>
      {% else %}
      <th scope="col player-col"></th>
      {% endif %}
    </tr>
  </thead>
  <tbody>

      {% for player in players %}
      {% if player.id|has_player_joined_tournament:tournament.id == True %}
      <tr>
        <td scope="row" class="player-row">{{player.user.username}}</td>
        <td class="player-row">Joined</td>
        <td class="player-row">
          {% if request.user == tournament.admin and player.user != tournament.admin %}
          <button class="btn btn-danger player-action-button btn-sm" data-bs-toggle="modal" data-bs-target="#id_remove_modal_{{player.user.id}}">Remove</button>
          {% elif request.user != tournament.admin and request.user == player.user %}
          <a hx-post="{% url 'tournament:remove_player' user_id=player.user.id tournament_id=player.tournament.id %}" hx-target="#body_container" hx-swap="innerHTML" class="btn btn-danger btn-sm player-action-button">Leave</a>
          {% elif request.user == tournament.admin and request.user == player.user %}
          <span style="font-weight: bold;">admin</span>
          {% endif %}
        </td>
      </tr>
      {% endif %}

      <!-- Removal Modals (one for each player) -->
      {% include 'tournament/snippets/player_remove_modal.html' with players=players %}

      {% endfor %}
      {% for invite in invites %}
      <tr>
        <td scope="row" class="player-row">{{invite.send_to.username}}</td>
        <td class="player-row">Invite pending</td>
        <td class="player-row">
          {% if request.user == tournament.admin %}
            <a hx-post="{% url 'tournament:uninvite' player_id=invite.send_to.id tournament_id=invite.tournament.id %}" hx-target="#body_container" hx-swap="innerHTML" class="btn btn-warning btn-sm player-action-button">Uninvite</a>
          {% elif request.user == invite.send_to %}
            <a hx-post="{% url 'tournament:join_tournament' pk=invite.id %}" hx-target="#body_container" hx-swap="innerHTML" class="btn btn-primary btn-sm player-action-button">Join</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
  </tbody>
</table>
</div>
{% endif %}
{% else %}
<p>Invalid state: {{tournament.get_state_string}}</p>
{% endif %}

<style type="text/css">
  @media only screen and (max-width: 500px) {
    .players-container {
      padding: 8px;
      background-color: #f2f2f2;
      border-radius: 8px;
    }

    .player-action-button {
      font-size: 12px;
    }

    .player-col {
      font-size: 12px;
    }

    .player-row {
      font-size: 12px;
      max-width: 150px;
      overflow: hidden;
      white-space: nowrap;
      text-overflow: ellipsis;
      text-align: left;
      vertical-align: middle;
    }
  }

  @media only screen and (min-width: 501px) {
    .players-container {
      padding: 16px;
      background-color: #f2f2f2;
      border-radius: 8px;
    }

    .player-col {
      font-size: 16px;
    }

    .player-row {
      font-size: 16px;
      max-width: 380px;
      overflow: hidden;
      white-space: nowrap;
      text-overflow: ellipsis;
      text-align: left;
      vertical-align: middle;
    }
  }
</style>

tournament/templates/tournament/snippets/tournament_state_snippet.html
<div class="overlay d-none" id="id_tournament_complete_spinner">
  <div class="d-flex justify-content-center">
    <div class="spinner-border" style="width: 70px; height: 70px;" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
</div>

<div class="tournament-state-container">
  <!-- COMPLETED -->
  {% if tournament_state.value == 2 %}

    {% include 'tournament/snippets/tournament_state_text_snippet.html' with tournament=tournament tournament_state=tournament_state %}
    <p class="mt-2">Completed on {{tournament.completed_at}}</p>
    {% if request.user == tournament.admin %}
    <div class="reopen-container">
      <p>Need to edit the Tournament? Undo completion to make changes.</p>
      <button class="btn btn-warning state-action-button" data-bs-toggle="modal" data-bs-target="#id_undo_completion_confirm">Undo completion</button>
    </div>
    {% endif %}


  <!-- ACTIVE -->
  {% elif tournament_state.value == 1 %}
    {% include 'tournament/snippets/tournament_state_text_snippet.html' with tournament=tournament tournament_state=tournament_state %}
    <p class="mt-2">Started on: {{tournament.started_at}}</p>
    {% if request.user == tournament.admin %}
      <div class="reopen-container mb-4">
        <p>Need to add/remove players or edit the Tournament Structure?</p>
        <button class="btn btn-warning state-action-button" data-bs-toggle="modal" data-bs-target="#id_undo_activate_confirm" id="id_deactivate_btn">De-activate</button>
      </div>
      <a class="btn btn-primary state-action-button" id="id_complete_tournament_btn" href="{% url 'tournament:complete' pk=tournament.id %}" onclick="onClickCompleteTournament()">Complete Tournament</a>
    {% endif %}

  <!-- INACTIVE -->
  {% else %}
    {% include 'tournament/snippets/tournament_state_text_snippet.html' with tournament=tournament tournament_state=tournament_state %}
    {% if request.user == tournament.admin %}
    <div class="d-flex flex-row justify-content-between">
      <a href="{% url 'tournament:start' pk=tournament.id %}" class="mt-3 btn btn-warning state-action-button" >Activate Tournament</a>
      <span style="width: 16px"></span>
      <a class="mt-3 btn btn-primary state-action-button" href="{% url 'tournament:tournament_backfill' pk=tournament.id %}">Backfill Tournament</a>
    </div>
    {% endif %}
  {% endif %}
</div>

<!-- Undo completion confirm modal -->
<div class="modal fade" id="id_undo_completion_confirm" tabindex="-1" aria-labelledby="Undo Completion Modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          Undo Completion
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body d-flex flex-column">
        <p>Are you sure?</p>
        <p class="text-danger" style="font-weight: bold;">All the eliminations & rebuys data will be lost!</p>
      </div>
      <div class="modal-footer" id="id_elim_model_button_container">
        <a href="{% url 'tournament:undo_complete' pk=tournament.id %}" class="btn btn-warning">Undo Completion</a>
      </div>
    </div>
  </div>
</div>

<!-- De-activate confirm modal -->
<div class="modal fade" id="id_undo_activate_confirm" tabindex="-1" aria-labelledby="de-activate Tournament Modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          De-activate
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body d-flex flex-column">
        <p>Are you sure?</p>
        <p class="text-danger" style="font-weight: bold;">All the tournament data will be deleted. Including:</p>
        <ol>
          <li>Rebuys</li>
          <li>Eliminations</li>
          <li>Analytics</li>
        </ol>
        <p>Essentially you'll be resetting the tournament completely.</p>
      </div>
      <div class="modal-footer">
        <a href="{% url 'tournament:undo_started' pk=tournament.id %}" class="btn btn-warning">De-activate</a>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  function onClickCompleteTournament(){
    document.getElementById("id_tournament_complete_spinner").classList.remove("d-none")
    document.getElementById("id_complete_tournament_btn").classList.add("disabled")
    document.getElementById("id_deactivate_btn").classList.add("disabled")
  }
</script>

<style type="text/css">
  .overlay {
    position: fixed;
    width: 100%;
    height: 100%;
    z-index: 1000;
    top: 40%;
    left: 0px;
    opacity: 1;
    filter: alpha(opacity=50);
  }

  @media only screen and (max-width: 500px) {
    .reopen-container {
      padding-top: 8px;
      padding-bottom: 8px;
      padding-left: 12px;
      padding-right: 12px;
      background-color: #f2f2f2;
      border-radius: 8px;
    }

    .state-action-button {
      font-size: 12px;
    }

    .tournament-state-container {
      font-size: 12px;
    }
  }

  @media only screen and (min-width: 501px) {
    .reopen-container {
      padding-top: 16px;
      padding-bottom: 16px;
      padding-left: 32px;
      padding-right: 32px;
      background-color: #f2f2f2;
      border-radius: 8px;
    }
  }

</style>