pokerstats/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from root.views import (
    contact_view,
    error_view,
    root_view,
)

from user.views import CustomPasswordChangeView

urlpatterns = [
    path('', root_view, name="home"),
    path('accounts/password/change/', CustomPasswordChangeView.as_view(), name="account_change_password"),
    path('accounts/', include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('contact/', contact_view, name="contact"),
    path('error/<str:error_message>/', error_view, name="error"),
    path('tournament/', include("tournament.urls"), name="tournament"),
    path('user/', include("user.urls"), name="user"),
    path('tournament_analytics/', include("tournament_analytics.urls"), name="tournament_analytics"),
    path('tournament_group/', include("tournament_group.urls"), name="tournament_group"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tournament/urls.py
from django.urls import include, path

from tournament.views import (
    complete_tournament,
    eliminate_player_from_tournament,
    invite_player_to_tournament,
    get_tournament_structure,
    join_tournament,
    rebuy_player_in_tournament,
    remove_player_from_tournament,
    split_eliminate_player_from_tournament,
    start_tournament,
    tournament_admin_view,
    tournament_backfill_view,
    tournament_create_view,
    tournament_edit_view,
    tournament_list_view,
    tournament_structure_create_view,
    tournament_view,
    undo_completed_at,
    undo_started_at,
    uninvite_player_from_tournament,
)

app_name = 'tournament'

urlpatterns = [
    path('complete/<int:pk>/', complete_tournament, name="complete"),
    path('create_tournament/', tournament_create_view, name="create_tournament"),
    path('create_tournament_structure/', tournament_structure_create_view, name="create_tournament_structure"),
    path('eliminate_player/<int:tournament_id>/<int:eliminator_id>/<int:eliminatee_id>/', eliminate_player_from_tournament, name="eliminate_player"),
    path('invite_player_to_tournament/<int:player_id>/<int:tournament_id>/', invite_player_to_tournament, name="invite_player"),
    path('get_tournament_structure/', get_tournament_structure, name="get_tournament_structure"),
    path('join_tournament/<int:pk>/', join_tournament, name="join_tournament"),
    path('player_rebuy/<int:player_id>/<int:tournament_id>/', rebuy_player_in_tournament, name="player_rebuy"),
    path('remove_player/<int:user_id>/<int:tournament_id>/', remove_player_from_tournament, name="remove_player"),
    path('split_eliminate_player/<int:tournament_id>/<str:eliminator_ids>/<int:eliminatee_id>/', split_eliminate_player_from_tournament, name="split_eliminate_player"),
    path('start/<int:pk>/', start_tournament, name="start"),
    path('tournament_admin_view/<int:pk>/', tournament_admin_view, name="tournament_admin_view"),
    path('tournament_backfill_view/<int:pk>/', tournament_backfill_view, name="tournament_backfill"),
    path('tournament_edit/<int:pk>/', tournament_edit_view, name="tournament_edit"),
    path('tournament_list/', tournament_list_view, name="tournament_list"),
    path('tournament_view/<int:pk>/', tournament_view, name="tournament_view"),
    path('undo_complete/<int:pk>/', undo_completed_at, name="undo_complete"),
    path('undo_started/<int:pk>/', undo_started_at, name="undo_started"),
    path('uninvite/<int:player_id>/<int:tournament_id>/', uninvite_player_from_tournament, name="uninvite"),
]

user/urls.py
from django.urls import include, path

from user.views import (
    cannot_edit_others_profile,
    user_profile_view,
)

app_name = 'user'

urlpatterns = [
    path('profile/<int:pk>/', user_profile_view, name="profile"),
    path('cannot_edit_others_profile/', cannot_edit_others_profile, name="cannot_edit_others_profile"),
]

templates/snippets/messages.html
{% if messages %}
<div class="messages-container">
    {% for message in messages %}
    {% if message.tags == 'error' %}
      <div class='alert alert-danger' role="alert">
        {{ message }}
      </div>
    {% elif message.tags == 'success' %}
      <div class='alert alert-success' role="alert">
        {{ message }}
      </div>
    {% else %}
      <div class='alert alert-primary' role="alert">
        {{ message }}
      </div>
    {% endif %}
    {% endfor %}
</div>

<script type="text/javascript">
  {% if messages %}
    window.scrollTo(0, 0);
  {% endif %}
</script>

<style type="text/css">
  @media only screen and (max-width: 500px) {
        .messages-container {
          margin-left: 8px;
          margin-right: 8px;
        }
    }

    @media only screen and (min-width: 501px) {
        .messages-container {
          margin-left: 16px;
          margin-right: 16px;
        }
    }
</style>
{% endif %}

templates/snippets/navigation.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">PokerStats</a>
    {% if request.user.is_authenticated %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tournament:tournament_list' %}">Tournaments</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:profile' pk=request.user.pk %}">Profile</a>
        </li>
      </ul>
      <span class="navbar-text">
        <a class="nav-link" href="{% url 'account_logout' %}">logout</a>
      </span>
    </div>
    {% endif %}
  </div>
</nav>