pokerstats/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from root.views import (
    contact_view,
    error_view,
    root_view,
)

from user.views import CustomPasswordChangeView

urlpatterns = [
    path('', root_view, name="home"),
    path('accounts/password/change/', CustomPasswordChangeView.as_view(), name="account_change_password"),
    path('accounts/', include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('contact/', contact_view, name="contact"),
    path('error/<str:error_message>/', error_view, name="error"),
    path('tournament/', include("tournament.urls"), name="tournament"),
    path('user/', include("user.urls"), name="user"),
    path('tournament_analytics/', include("tournament_analytics.urls"), name="tournament_analytics"),
    path('tournament_group/', include("tournament_group.urls"), name="tournament_group"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tournament/urls.py
from django.urls import include, path

from tournament.views import (
    complete_tournament,
    eliminate_player_from_tournament,
    invite_player_to_tournament,
    get_tournament_structure,
    join_tournament,
    rebuy_player_in_tournament,
    remove_player_from_tournament,
    split_eliminate_player_from_tournament,
    start_tournament,
    tournament_admin_view,
    tournament_backfill_view,
    tournament_create_view,
    tournament_edit_view,
    tournament_list_view,
    tournament_structure_create_view,
    tournament_view,
    undo_completed_at,
    undo_started_at,
    uninvite_player_from_tournament,
)

app_name = 'tournament'

urlpatterns = [
    path('complete/<int:pk>/', complete_tournament, name="complete"),
    path('create_tournament/', tournament_create_view, name="create_tournament"),
    path('create_tournament_structure/', tournament_structure_create_view, name="create_tournament_structure"),
    path('eliminate_player/<int:tournament_id>/<int:eliminator_id>/<int:eliminatee_id>/', eliminate_player_from_tournament, name="eliminate_player"),
    path('invite_player_to_tournament/<int:player_id>/<int:tournament_id>/', invite_player_to_tournament, name="invite_player"),
    path('get_tournament_structure/', get_tournament_structure, name="get_tournament_structure"),
    path('join_tournament/<int:pk>/', join_tournament, name="join_tournament"),
    path('player_rebuy/<int:player_id>/<int:tournament_id>/', rebuy_player_in_tournament, name="player_rebuy"),
    path('remove_player/<int:user_id>/<int:tournament_id>/', remove_player_from_tournament, name="remove_player"),
    path('split_eliminate_player/<int:tournament_id>/<str:eliminator_ids>/<int:eliminatee_id>/', split_eliminate_player_from_tournament, name="split_eliminate_player"),
    path('start/<int:pk>/', start_tournament, name="start"),
    path('tournament_admin_view/<int:pk>/', tournament_admin_view, name="tournament_admin_view"),
    path('tournament_backfill_view/<int:pk>/', tournament_backfill_view, name="tournament_backfill"),
    path('tournament_edit/<int:pk>/', tournament_edit_view, name="tournament_edit"),
    path('tournament_list/', tournament_list_view, name="tournament_list"),
    path('tournament_view/<int:pk>/', tournament_view, name="tournament_view"),
    path('undo_complete/<int:pk>/', undo_completed_at, name="undo_complete"),
    path('undo_started/<int:pk>/', undo_started_at, name="undo_started"),
    path('uninvite/<int:player_id>/<int:tournament_id>/', uninvite_player_from_tournament, name="uninvite"),
]

tournament_group/urls.py
from django.urls import include, path

from tournament_group.views import (
	add_tournament_to_group,
	add_user_to_group,
	fetch_rbg_colors,
	fetch_tournament_group_eliminations_and_rebuys_data,
	fetch_tournament_group_net_earnings_data,
	fetch_tournament_group_pot_contributions_data,
	fetch_tournament_group_touraments_played_data,
	remove_tournament_from_group,
	remove_user_from_group,
	tournament_group_create_view,
	tournament_group_update_view,
	update_tournament_group_title,
	view_tournament_group
)

app_name = 'tournament_group'

urlpatterns = [
    path('add_user_to_group/<int:user_id>/<int:tournament_group_id>/', add_user_to_group, name="add_user_to_group"),
    path('add_tourament_to_group/<int:tournament_id>/<int:tournament_group_id>/', add_tournament_to_group, name="add_tournament_to_group"),
    path('remove_tournament_from_group/<int:tournament_id>/<int:tournament_group_id>/', remove_tournament_from_group, name="remove_tournament_from_group"),
    path('fetch_elim_and_rebuys_data/<int:pk>/', fetch_tournament_group_eliminations_and_rebuys_data, name="fetch_elim_and_rebuys_data"),
    path('fetch_net_earnings_data/<int:pk>/', fetch_tournament_group_net_earnings_data, name="fetch_net_earnings_data"),
    path('fetch_pot_contributions_data/<int:pk>/', fetch_tournament_group_pot_contributions_data, name="fetch_pot_contributions_data"),
    path('fetch_rbg_colors/<int:num_colors>/', fetch_rbg_colors, name="fetch_rbg_colors"),
    path('fetch_tournaments_played_data/<int:pk>/', fetch_tournament_group_touraments_played_data, name="fetch_tournaments_played_data"),
    path('create/', tournament_group_create_view, name="create"),
    path('remove_user_from_group/<int:user_id>/<int:tournament_group_id>/', remove_user_from_group, name="remove_user_from_group"),
    path('update/<int:pk>/', tournament_group_update_view, name="update"),
    path('update_tournament_group_title/<int:tournament_group_id>/<path:title>/', update_tournament_group_title, name="update_tournament_group_title"),
    path('view_tournament_group/<int:pk>/', view_tournament_group, name="view"),
]

user/urls.py
from django.urls import include, path

from user.views import (
    cannot_edit_others_profile,
    user_profile_view,
)

app_name = 'user'

urlpatterns = [
    path('profile/<int:pk>/', user_profile_view, name="profile"),
    path('cannot_edit_others_profile/', cannot_edit_others_profile, name="cannot_edit_others_profile"),
]

tournament/models.py
import json
from decimal import Decimal
from django.db import models
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from enum import Enum
from io import StringIO
from itertools import chain

from user.models import User

PERCENTAGE_VALIDATOR = [MinValueValidator(0), MaxValueValidator(100)]

from tournament.util import build_placement_string, PlayerTournamentPlacement, DID_NOT_PLACE_VALUE


"""
Checks if
(1) the payout_percentages sum to 100
(2) every value in payout_percentages is between 0 and 100.
"""
def validate_percentages(payout_percentages):
	total = 0
	for pct in payout_percentages:
		if pct > 100 or pct < 0:
			raise ValidationError("Each payout percentage must be between 0 and 100.")
		total += pct
	if total != 100:
		raise ValidationError("Payout Percentages must sum to 100")
	
class TournamentStructureManager(models.Manager):

	# USED FOR TESTING ONLY... create new fn using the USER instead of user_email.
	# from tournament.models import TournamentStructure
	# TournamentStructure.objects.create_tournament_struture_test("mitchs tournmanet structure", "mitch@tabian.ca", 60, 10, (70,20,10), True)
	def create_tournament_struture_test(self, title, user_email, buyin_amount, bounty_amount, payout_percentages, allow_rebuys):
		user = User.objects.get_by_email(user_email)
		validate_percentages(payout_percentages)
		tournament_structure = self.model(
			title=title,
			user=user,
			buyin_amount=buyin_amount,
			bounty_amount=bounty_amount,
			payout_percentages=payout_percentages,
			allow_rebuys=allow_rebuys
		)
		tournament_structure.save(using=self._db)
		return tournament_structure

	def create_tournament_struture(self, title, user, buyin_amount, bounty_amount, payout_percentages, allow_rebuys):
		validate_percentages(payout_percentages)
		tournament_structure = self.model(
			title=title,
			user=user,
			buyin_amount=buyin_amount,
			bounty_amount=bounty_amount,
			payout_percentages=payout_percentages,
			allow_rebuys=allow_rebuys
		)
		tournament_structure.save(using=self._db)
		return tournament_structure

	# ONLY USE FOR TESTING
	def get_structures_by_user_email(self, user_email):
		user = User.objects.get_by_email(user_email)
		structures = super().get_queryset().filter(user=user)
		return structures

	def get_structures_by_user(self, user):
		structures = super().get_queryset().filter(user=user)
		return structures

	def get_by_id(self, id):
		try:
			structure = self.get(pk=id)
		except TournamentStructure.DoesNotExist:
			structure = None
		return structure

"""
Note: buyin_amount already takes into account the bounty_amount. 
Ex: If buyin_amount=60 and bounty_amount=10, the total amount a user must pay to play is 60.
"""
class TournamentStructure(models.Model):
	title 					= models.CharField(max_length=254, blank=False, null=False)

	# The user that created this tournament structure.
	user 					= models.ForeignKey(User, on_delete=models.CASCADE)

	# Cost to buy into this tournament.
	buyin_amount			= models.DecimalField(max_digits=9, decimal_places=2, blank=False, null=False)

	# Optional. Not all tournaments must have bounties. If this is null, it is not a bounty tournament.
	bounty_amount			= models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
	
	"""
	Ex: (70, 20, 10)
	"""
	payout_percentages		= ArrayField(
								models.DecimalField(
									max_digits=3,
									decimal_places=0,
									default=0,
									validators=PERCENTAGE_VALIDATOR
								),
								validators=[validate_percentages]
							)
	allow_rebuys 			= models.BooleanField(default=False)


	objects = TournamentStructureManager()

	def __str__(self):
		return self.title

	def is_bounty_tournament(self):
		if self.bounty_amount != None:
			return True
		else:
			return False

	"""
	Builds a JSON representations of a TournamentStructure.
	"""
	def buildJson(self):
		data = {}
		data['pk'] = self.pk
		data['title'] = self.title
		data['buyin_amount'] = f"{self.buyin_amount}"
		if self.bounty_amount != None:
			data['bounty_amount'] = f"{self.bounty_amount}"
		payout_percentages = []
		for pct in self.payout_percentages:
			payout_percentages.append(f"{pct}")
		data['payout_percentages'] = payout_percentages
		return json.dumps(data)

class TournamentManager(models.Manager):

	def create_tournament(self, title, user, tournament_structure):
		if tournament_structure.user != user:
			raise ValidationError("You cannot use a Tournament Structure that you don't own.")
		tournament = self.model(
			title=title,
			admin=user,
			tournament_structure=tournament_structure
		)
		tournament.save(using=self._db)

		# The admin automatically becomes a player in the tournament
		player = TournamentPlayer.objects.create_player_for_tournament(
			user_id = user.id,
			tournament_id = tournament.id	
		)

		return tournament

	# from tournament.models import Tournament
	# Tournament.objects.email_tournament_results(1)
	"""
	Email the results of a tournament to all the players.
	This is mainly for data backup reasons. Like if for some reason an admin accidentally "undo-completion" and 
	their data is lost. At least they'll have this text backup.
	"""
	def email_tournament_results(self, tournament_id):
		try:
			tournament = self.get(pk=tournament_id)
			subject = f"{settings.ACCOUNT_EMAIL_SUBJECT_PREFIX} results for tournament."
			message = f"Here are the results for the Tournament you played on {tournament.completed_at}."
			payout_string = '('
			for i, pct in enumerate(tournament.tournament_structure.payout_percentages):
				if i != 0:
					payout_string += ', '
				payout_string += f'{build_placement_string(i)}: {pct}%'
			payout_string += ')'
			is_bounty_tournament = f'{tournament.tournament_structure.buyin_amount != None}'
			allow_rebuys = f'{tournament.tournament_structure.allow_rebuys}'
			buyin_amount = f'${tournament.tournament_structure.buyin_amount}'
			bounty_amount = tournament.tournament_structure.bounty_amount
			if bounty_amount == None:
				bounty_amount = "N/A"
			else:
				bounty_amount = f"${bounty_amount}"
			
			players = TournamentPlayer.objects.get_tournament_players(
				tournament_id = tournament.id
			)
			players_string = ''
			total_players = 0
			player_rebuys_string = '\n'
			total_rebuys = 0
			for i, player in enumerate(players):
				total_players += 1
				if i != 0:
					players_string += ', '
				players_string += f'{player.user.username}'
				rebuys = TournamentRebuy.objects.get_rebuys_for_player(
					player = player
				)
				if len(rebuys) > 0:
					total_rebuys += len(rebuys)
					player_rebuys_string += f'\t\t\t\t{player.user.username}: ({len(rebuys)})\n'

			if not tournament.tournament_structure.allow_rebuys:
				player_rebuys_string = "N/A"

			eliminations = TournamentElimination.objects.get_eliminations_by_tournament(
				tournament_id = tournament.id,
			)
			split_eliminations = TournamentSplitElimination.objects.get_split_eliminations_by_tournament(
				tournament_id = tournament.id,
			)
			combined_eliminations = list(chain(eliminations, split_eliminations))
			combined_eliminations.sort(key=lambda elimination: elimination.eliminated_at)
			player_eliminations_string = '\n'
			total_eliminations = 0
			for elimination in combined_eliminations:
				total_eliminations += 1
				if type(elimination) is TournamentElimination:
					player_eliminations_string += f'\t\t\t\t{elimination.eliminator.user.username}: eliminated {elimination.eliminatee.user.username} at {elimination.eliminated_at}\n'
				if type(elimination) is TournamentSplitElimination:
					player_split_elimination_string = [f"{player.user.username}, " for player in elimination.eliminators.all()]
					player_eliminations_string += f'\t\t\t\t{player_split_elimination_string}: eliminated {elimination.eliminatee.user.username} at {elimination.eliminated_at}\n'
			
			results = TournamentPlayerResult.objects.get_results_for_tournament(
				tournament_id = tournament.id
			).order_by("placement")
			placement_string = '\n'
			for result in results:
				placement_string += f'\t\t\t\t{build_placement_string(result.placement)}: {result.player.user.username}\n'
				
			total_pot_value = f'${round(Decimal((len(players) + total_rebuys) * tournament.tournament_structure.buyin_amount), 2)}'

			f = StringIO()
			f.write(f'''\n
				Tournament Title: {tournament.title}\n
				Completed on: {tournament.completed_at}\n
				Bounty Tournament? {is_bounty_tournament}\n
				Allow rebuys? {allow_rebuys}\n
				Payout percentages: {payout_string}\n
				Buyin amount: {buyin_amount}\n
				Bounty amount: {bounty_amount}\n
				Players: {players_string}\n
				Num players: {total_players}\n
				Placements: {placement_string}
				Num rebuys: {total_rebuys}\n
				Player rebuys: {player_rebuys_string}
				Player Eliminations: {player_eliminations_string}
				Total Tournament value: {total_pot_value}
				\n''')
			f.seek(0)
			msg = MIMEBase('application', "octet-stream")
			msg.set_payload(f.read())
			encoders.encode_base64(msg)
			msg.add_header(
				'Content-Disposition',
				'attachment',
				filename='tournament_summary.txt'
			)
			players = TournamentPlayer.objects.get_tournament_players(
				tournament_id = tournament.id
			)
			emails = [player.user.email for player in players]
			mail = EmailMessage(subject, message, settings.EMAIL_HOST_USER, emails)
			mail.attach(msg)
			mail.send()
		except Exception as e:
			# Fail silently.
			# TODO add bugsnag call here.
			pass

	def complete_tournament(self, user, tournament_id):
		tournament = self.get(pk=tournament_id)
		try:
			if tournament.admin != user:
				raise ValidationError("You cannot update a Tournament if you're not the admin.")

tournament/templates/tournament/tournament_admin_view.html
{% extends "base.html" %}

{% block head_title %}Tournament admin{% endblock %}

{% block content %}

<div class="container" id="parent">
  <div class="row">
    <div class="offset-md-1 col-md-10">

    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'tournament:tournament_view' pk=tournament.id %}">Tournament</a></li>
        <li class="breadcrumb-item active" aria-current="page">Admin view</li>
      </ol>
    </nav>

      <!-- Admin View title-->
      <h2>Admin View</h2>
      <!-- Tournament Title -->
      <h6>{{tournament.title}}</h6>
      <hr>

      <!-- TournamentPlayerData table -->
      {% if player_tournament_data %}
        <div class="tournament-details-group">
          {% if is_bounty_tournament == True or allow_rebuys == True %}
            {% include 'tournament/snippets/player_admin_table_complex.html' with player_tournament_data=player_tournament_data allow_rebuys=allow_rebuys is_bounty_tournament=is_bounty_tournament %}
          {% else %}
            {% include 'tournament/snippets/player_admin_table_simple.html' with player_tournament_data=player_tournament_data %}
          {% endif %}
        </div>
      {% endif %}

      <!-- Tournament state -->
      <h5 class="mt-4">State</h5>
      <hr>
      <div class="tournament-details-group">
        {% include 'tournament/snippets/tournament_state_snippet.html' with tournament=tournament tournament_state=tournament_state %}
      </div>


    </div>
  </div>
</div>

<style type="text/css">

  hr {
    margin-top: 8px;
    margin-bottom: 8px;
  }

  @media only screen and (max-width: 500px) {
    .tournament-details-group {
      margin-bottom: 16px;
      font-size: 12px;
    }
  }

  @media only screen and (min-width: 501px) {
    .tournament-details-group {
      padding-left: 16px;
      padding-right: 16px;
      padding-bottom: 16px;
      margin-bottom: 16px;
      font-size: 16px;
    }
  }
</style>
{% endblock content %}

tournament/templates/tournament/tournament_edit_view.html
{% extends "base.html" %}

{% block head_title %}Edit Tournament{% endblock %}

{% block content %}

<div class="container" id="parent">
  <div class="row">
    <div class="offset-md-1 col-md-10">
      <form method="POST">
        {% csrf_token %}

        <!-- Title -->
        <h5>Title</h5>
        <hr>
        <div class="tournament-details-group">
          <input type="text" name="title" class="form-control tournament-title" placeholder="Title" required id="id_title" value="{{form.title.value}}">
        </div>

        <!-- Tournament Structure -->
        <h5>Structure</h5>
        <hr>

        <div class="tournament-details-group">
          <select name="tournament_structure" id="id_tournament_structure" class="form-select mb-3 mt-3" aria-label="Select Tournament Structure">
            {% for structure in form.tournament_structure.field.queryset.all %}
              {% if structure == initial_selected_structure %}
              <option value="{{structure.pk}}" selected>{{structure}}</option>
              {% else %}
              <option value="{{structure.pk}}">{{structure}}</option>
              {% endif %}
            {% endfor %}
          </select>

          <!-- Add all the tables for Tournament Structures, but hide them. They get revealed if they are selected from the selector above -->
          {% for structure in tournament_structures %}
            <div class="d-none" id="id_tournament_structure_table_{{structure.pk}}">
              {% include 'tournament/snippets/tournament_structure_table.html' with tournament_structure=structure %}
            </div>
          {% endfor %}


          <div class="mt-3">
            <a href="{% url 'tournament:create_tournament_structure' %}?next=/tournament/tournament_edit/{{tournament_pk}}/">Create new Tournament Structure</a>
          </div>
        </div>

        <button id="id_submit_button" class="btn btn-primary" type="submit">Save</button>
    </form>
	 </div>
  </div>
</div>

<style type="text/css">

  @media only screen and (max-width: 500px) {
    .select-container {
      width: 100%;
    }

    .tournament-title {
      margin-top: 16px;
    }

    #id_save_tournament:hover {
      background: #cccccc;
      cursor: pointer;
    }

    #id_save_tournament {
      color: #0275d8;
      margin: auto;
    }

    .tournament-details-group {
      margin-bottom: 24px;
    }
  }

  @media only screen and (min-width: 501px) {
    .tournament-title {
      margin-top: 16px;
    }

    #id_save_tournament:hover {
      background: #cccccc;
      cursor: pointer;
    }

    #id_save_tournament {
      color: #0275d8;
      margin: auto;
    }

    .tournament-details-group {
      padding-left: 16px;
      padding-right: 16px;
      padding-bottom: 16px;
      margin-bottom: 16px;
    }
  }

  hr {
    margin-top: 8px;
    margin-bottom: 8px;
  }


</style>

<script type="text/javascript">
  var structureSelector = document.getElementById("id_tournament_structure")

  structureSelector.addEventListener("change", function() {
    var options = structureSelector.querySelectorAll("option");
    for (let index = 0; index < options.length; index++) {
      if (options[index].selected) {
        showTournamentStructureTable(options[index].value)
      } else {
        hideTournamentStructureTable(options[index].value)
      }
    }
  })

  function showTournamentStructureTable(tournament_structure_pk) {
    // Find the table that matches the primary key of this TournamentStructure and make it visible.
    var table = document.getElementById("id_tournament_structure_table_" + tournament_structure_pk)
    table.classList.remove("d-none")
  }

  function hideTournamentStructureTable(tournament_structure_pk) {
    // Find the table that matches the primary key of this TournamentStructure and make it invisible.
    var table = document.getElementById("id_tournament_structure_table_" + tournament_structure_pk)
    if (!table.classList.contains("d-none")) {
      table.classList.add("d-none")
    }
  }

  showTournamentStructureTable("{{initial_selected_structure.pk}}")

</script>

{% endblock content %}

tournament/templates/tournament/tournament_view.html
{% extends "base.html" %}

{% block head_title %}Tournaments{% endblock %}

{% block content %}

<div class="container" id="parent">
  <div class="row">
    <div class="offset-md-1 col-md-10">

      <!-- title -->
      <h2>
        <div class="d-flex justify-content-between">
          <span class="tournament-title">{{tournament.title}}</span>
          {% if request.user == tournament.admin and tournament.get_state_string == "INACTIVE" %}
          <a href="{% url 'tournament:tournament_edit' pk=tournament.id %}">
            <svg id="id_edit_tournament_structure" xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
            </svg>
          </a>
          {% endif %}
        </div>
      </h2>
      <div class="tournament-state-header-container">
        {% include 'tournament/snippets/tournament_state_text_snippet.html' with tournament=tournament tournament_state=tournament_state %}
      </div>


      <!-- Admin -->
      {% if request.user == tournament.admin and tournament.get_state_string == 'ACTIVE' %}
      <h5>Admin</h5>
      <hr>
      <div class="tournament-details-group">
        <a class="mt-2 btn btn-primary admin-btn" href="{% url 'tournament:tournament_admin_view' pk=tournament.id %}">Admin view</a>
      </div>
      {% endif %}

      <!-- Timeline -->
      <!-- Only show timeline if tournament is ACTIVE or COMPLETED. Also if it is not a backfill. -->
      {% if tournament.get_state_string == "ACTIVE" or tournament.get_state_string == "COMPLETED" %}
      {% if events|length > 0 %}
      <h5>Timeline</h5>
      <hr>
      <div class="tournament-details-group" id="id_timeline_group">
        {% include 'tournament/snippets/tournament_events_timeline.html' %}
      </div>
      {% endif %}
      {% endif %}

      <!-- Players -->
      <h5>
        {% if tournament.completed_at != None %}
          Results
        {% else %}
          Players
        {% endif %}
      </h5>
      <hr>
      <div class="tournament-details-group">
        {% if tournament.get_state_string == "INACTIVE" %}
        {% include 'tournament/snippets/tournament_players_inactive_state.html' with players=players invites=invites %}
        {% elif tournament.get_state_string == "ACTIVE" %}
        {% include 'tournament/snippets/tournament_players_active_state.html' with player_tournament_data=player_tournament_data allow_rebuys=allow_rebuys is_bounty_tournament=is_bounty_tournament %}
        {% else %}
        {% include 'tournament/snippets/confirm_join.html' with players=players %}
        {% include 'tournament/snippets/tournament_players_completed_state.html' with players=players %}
        {% endif %}

        {% if request.user == tournament.admin and tournament.get_state_string == "INACTIVE" %}
          <div id="id_send_invite_container" class="mt-4">
            <h6>Invite Players</h6>
            <input hx-get="{% url 'tournament:tournament_view' pk=tournament.id %}" hx-target="#body_container" hx-swap="innerHTML" hx-trigger="input delay:0.3s" type="text" name="search" id="id_search" class="form-control mt-3" placeholder="Add players" aria-label="Add players" value="{{search}}">
            {% include 'tournament/snippets/user_search_results.html' %}
          </div>
        {% endif %}
      </div>


      <!-- Warning -->
      {% include 'tournament/snippets/joined_status_snippet.html' with players=players tournament=tournament %}

      <!-- Tournament Structure -->
      <h5>Structure</h5>
      <hr>
      <div class="tournament-details-group">
        {% include 'tournament/snippets/tournament_structure_table.html' with tournament_structure=tournament.tournament_structure %}
      </div>


      <!-- Tournament state -->
      <h5>State</h5>
      <hr>
      <div class="tournament-details-group">
        {% include 'tournament/snippets/tournament_state_snippet.html' with tournament=tournament tournament_state=tournament_state %}
      </div>
	 </div>
  </div>
</div>

<style type="text/css">

  hr {
    margin-top: 8px;
    margin-bottom: 8px;
  }

  @media only screen and (max-width: 500px) {
    .tournament-details-group {
      margin-bottom: 16px;
      font-size: 12px;
    }

    .admin-btn {
      font-size: 12px;
    }
  }

  @media only screen and (min-width: 501px) {
    .tournament-details-group {
      padding-left: 16px;
      padding-right: 16px;
      padding-bottom: 16px;
      margin-bottom: 16px;
      font-size: 16px;
    }
  }


  #id_edit_tournament_structure:hover {
    background: #cccccc;
    cursor: pointer;
  }

  #id_edit_tournament_structure {
    color: #0275d8;
  }

  .tournament-title {
    max-width: 90%;
  }

  .tournament-state-header-container {
    font-size: 12px;
    margin-bottom: 20px;
  }
</style>

<script src="https://unpkg.com/htmx.org@1.8.5"></script>

<script type="text/javascript">

  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })


</script>

{% endblock content %}